<div class="boxContentFull">
    <div class="category-title">
        <h1>100% USA Made E-Liquids</h1>
        <p>
            The fun is the flavor, and VaporFi has more flavors than anyone. Our e-liquids are made from FDA registered labs using better than food grade flavorings for a quality taste every time. Choose from an in-house blend or customize your own combo giving you over 30,000 choices. Bet you can’t try them all!
        </p>
    </div>
    <div class="boxContentFullMain clearer" id="boxSubCategoryContent">
        <a href="e-liquid-cartridges/custom-blend.html" id="cat-custom-blend" class="category-button lgrayButtonSml category-button-long">
            <img src="skin/frontend/default/vaporfi_theme/images/vz-cat-custom-blend.png" alt="Custom Blend"/>
            Custom Blend
        </a>
        <a href=e-liquid-cartridges/top-blends/" id="cat-top-blends" class="category-button lgrayButtonSml category-button-long">
            <img src="skin/frontend/default/vaporfi_theme/images/vz-cat-top-blends.png" alt="Top Blends"/>
            Top Blends
        </a>
        <a href="e-liquid-cartridges/tobacco-flavored-e-liquids/" id="cat-tobacco-flavors" class="category-button lgrayButtonSml category-button-long last">
            <img src="skin/frontend/default/vaporfi_theme/images/vz-cat-tobacco-flavors.png" alt="Tobacco Flavors"/>
            Tobacco Flavors
        </a>
        <a href="e-liquid-cartridges/menthol-flavored-e-liquids/" id="cat-menthol-flavors" class="category-button lgrayButtonSml category-button-long">
            <img src="skin/frontend/default/vaporfi_theme/images/vz-cat-menthol-flavors.png" alt="Menthol Flavors"/>
            Menthol Flavors
        </a>
        <a href="e-liquid-cartridges/dessert-flavored-e-liquids/" id="cat-dessert-flavors" class="category-button lgrayButtonSml category-button-long">
            <img src="skin/frontend/default/vaporfi_theme/images/vz-cat-dessert-flavors.png" alt="Dessert Flavors"/>
            Dessert Flavors
        </a>
        <a href="e-liquid-cartridges/fruit-flavored-e-liquids/" id="cat-fruit-flavors" class="category-button lgrayButtonSml category-button-long last">
            <img src="skin/frontend/default/vaporfi_theme/images/vz-cat-fruit-flavors.png" alt="Fruit Flavors"/>
            Fruit Flavors
        </a>
        <a href="e-liquid-cartridges/other-flavored-e-liquids/" id="cat-other-flavors" class="category-button lgrayButtonSml category-button-long">
            <img src="skin/frontend/default/vaporfi_theme/images/vz-cat-other-flavors.png" alt="Other Flavors"/>
            Other Flavors
        </a>
        <a href="e-liquid-cartridges/pink-ribbon-blends/" id="cat-pink-ribbon-blends" class="category-button lgrayButtonSml category-button-long">
            <img src="skin/frontend/default/vaporfi_theme/images/vz-cat-pink-ribbon-blends.png" alt="Pink-Ribbon Blends"/>
            Pink-Ribbon Blends
        </a>
        <a href="e-liquid-cartridges/reserve-collection/" id="cat-reserve-collections" class="category-button lgrayButtonSml category-button-long premium-blend last">
            Reserve Collections
        </a>
    </div>
    <div class="boxBottom3">&nbsp;</div>
</div>



<!-- Menthol Flavored e-Liquids  -->
<span id="cat-menthol-flavors" class="selected category-button lgrayButtonSml category-button-long">
    <a href="e-liquid-cartridges/menthol-flavored-e-liquids/" id="cat-menthol-flavors" class="category-button lgrayButtonSml category-button-long">
        <img src="skin/frontend/default/vaporfi_theme/images/vz-cat-menthol-flavors.png" alt="Menthol Flavors"/>
        Menthol Flavors
    </a>
</span>

<div class="category-title">
    <h1>Menthol Flavored e-Liquids</h1> <p>Refreshing, cool, and clean is how menthol is supposed to be and it’s just what we offer – only in a whole slew of varieties. Our menthol e-liquid flavors are crisp and loaded with flavor, so enjoy them as they are or get inspired and blend them to your own specifications.</p>
</div>
<div class="boxBottom3">&nbsp;</div>
