<div id="mainOffers">
    <div class="offerSection" id="grandReserveSection">
        <h3>
            <span class="new">New!</span>
            Grand Reserve
            <br />
            Collection
        </h3>
        <a href="/e-liquid-cartridges/reserve-collection/grand-reserve/" class="btn-link-full offer-img-link">
            <img src="/skin/frontend/default/vaporfi_theme/images/img-grand-reserve-home-offer.jpg" alt="Grand Reserve Collection" width="284" height="152" />
        </a>
        <h4>Award winning refined flavors for refined vapers</h4>
        <a href="/e-liquid-cartridges/reserve-collection/grand-reserve/" class="greenButtonSml" style="width:130px;">shop now</a>
        <div class="offerSectionBottom"></div>
    </div>
    <div class="offerSection">
        <h3>
            New
            <span>VOX 100</span>
            TC
        </h3>
        <a href="#" class="btn-link-full offer-img-link">
            <img src="/skin/frontend/default/vaporfi_theme/images/img-vox-100-tc-home-offer.jpg" alt="VOX 100 TC" width="284" height="152" />
        </a>
        <h4>Vox 100 TC Now Available</h4>
        <p>About as advanced as it can get, Temperature Control + VOX 100W power! </p>
        <a href="#" class="greenButtonSml" style="width:130px;">Shop VOX 100 TC</a>
        <div class="offerSectionBottom"></div>
    </div>
    <div id="stepFlavorSection" class="offerSection last">
        <h3>Custom E-Liquids</h3>
        <div class="stepFlavor">
            <a href="/e-liquid-cartridges/custom-blending/">
                <img src="/skin/frontend/default/vaporfi_theme/images/mixing_step_1.png" alt="Choose Your Strength" width="51" height="50" />
            </a>
            <h4>Choose Your Strength</h4>
            <p>You pick the level of nicotine you want to vape.</p>
        </div>
        <div class="stepFlavor">
            <a href="/e-liquid-cartridges/custom-blending/">
                <img src="/skin/frontend/default/vaporfi_theme/images/mixing_step_2.png" alt="Choose Your Flavors" width="51" height="50" />
            </a>
            <h4>Choose Your Flavors</h4>
            <p>Mix and match up to three flavors from our huge list of tasty e-liquids.</p>
        </div>
        <div class="stepFlavor">
            <a href="/e-liquid-cartridges/custom-blending/">
                <img src="/skin/frontend/default/vaporfi_theme/images/mixing_step_3.png" alt="Enjoy The Freedom" width="51" height="50" />
            </a>
            <h4>We Make it Fresh</h4>
            <p>Our expert Vapetenders™ mix your blend fresh. No pre-packaged e-liquids here.</p>
        </div>
        <a href="/e-liquid-cartridges/custom-blending/" class="greenButtonSml" style="width:140px;">Start Blending</a>
        <div class="offerSectionBottom"></div>
    </div>
    <div class="clear"></div>
</div>





<div id="howitworks">
    <h2>How do vaporizers work?</h2>
    <p>E-cigarettes and vaporizers have taken the world by storm by allowing all the pleasures of traditional smoking without the bad breath, stinky clothes, tremendous cost, and harmful effects of tobacco.</p>
    <a href="#" class="greenButton" id="howitworks-link">Read More</a>
</div>
<img src="/skin/frontend/default/vaporfi_theme/images/how_it_works_img_1.png" id="howitworksImg" width="469" height="339" />
<div class="boxBottom1"></div>





<div id="testimonial1">
    <p>“I cannot speak highly enough about these awesome products from VaporFi. I had wanted to get into better e-cigarette models for a while, and in doing my research I learned about this company. It’s great to see this kind of performance; my enjoyment of vaping has increased 10-fold!”
        <a href="#">read more</a>
        <span>- Liz R. Dallas, TX</span>
    </p>
</div>
<div id="testimonial2">
    <p>“I am a vapor connoisseur, and these are top of the line. I am not only pleased with the selection of excellent battery models, but how powerful they all are. 2 thumbs up for the great flavors- not many brands out there give the option of blending them yourself, and this takes things to another level!”
        <a href="#">read more</a>
        <span>- David L. New York, NY</span>
    </p>
</div>
<img src="/skin/frontend/default/vaporfi_theme/images/testimonial_img_1.png" id="testimonialImg" width="211" height="201" />
<div class="clear"></div>
<div class="boxBottom1"></div>


<a href="#" class="btn-link-full">
    <img src="/skin/frontend/default/vaporfi_theme/images/banner_home_bottom_sample_3_pack.png" />
</a>
<div class="clear"></div>
<div class="boxBottom1"></div>


<div class="boxContentFullMain">
    <a href="javascript: void(0)" title="30 Day Money Back Guarantee" class="bottom-banner top pop-up-link" id="GuaranteePop">
        <img src="/skin/frontend/default/vaporfi_theme/images/moneyback-orange.png" width="450" height="150" alt="30 Day Money Back Guarantee">
    </a>
    <a href="#" title="VaporFi Gift Cards" class="bottom-banner top">
        <img src="/skin/frontend/default/vaporfi_theme/images/gift-card-banner.png" width="450" height="150" alt="VaporFi Gift Cards">
    </a>
    <a href="#" title="Why e-Liquid Rocks" class="bottom-banner">
        <img src="/skin/frontend/default/vaporfi_theme/images/eliquid-rocks-green.png" width="450" height="150" alt="Why e-Liquid Rocks">
    </a>
    <a href="#" title="Refer-A-Friend" class="bottom-banner">
        <img src="/skin/frontend/default/vaporfi_theme/images/refer-a-friend-banner.png" width="450" height="150" alt="Refer-A-Friend">
    </a>
    <div class="clear">&nbsp;</div>
</div>


<!-- MOBILE MENU  -->
<ul id="mobile-mainNav">
    <li class="nav-1 parent">
        <a title="E-Liquid &amp; Cartridges" href="/e-liquid-cartridges">E-Liquids</a>
        <a href="javascript: void(0)" class="sub-nav-btn"></a>
        <ul>
            <li><a title="Custom Blending" href="/e-liquid-cartridges/custom-blending">Custom Blending</a></li>
            <li><a title="Sampler 3-Pack" href="/e-liquid-cartridges/sampler-3-pack">Sampler 3-Pack</a></li>
            <li><a title="Top Blends" href="/e-liquid-cartridges/top-blends">Top Blends</a></li>
            <li><a title="Tobacco Flavors" href="/e-liquid-cartridges/tobacco-flavors">Tobacco Flavors</a></li>
            <li><a title="Menthol Flavors" href="/e-liquid-cartridges/menthol-flavors">Menthol Flavors</a></li>
            <li><a title="Fruit Flavors" href="/e-liquid-cartridges/fruit-flavors">Fruit Flavors</a></li>
            <li><a title="Dessert Flavors" href="/e-liquid-cartridges/dessert-flavors">Dessert Flavors</a></li>
            <li><a title="Other Flavors" href="/e-liquid-cartridges/other-flavors">Other Flavors</a></li>
            <li><a title="Flavor Enhancers" href="/e-liquid-cartridges/flavor-enhancers">Flavor Enhancers</a></li>
            <li><a title="Reserve &amp; Grand Reserve Collection" href="/e-liquid-cartridges/reserve-collection">Reserve &amp; Grand Reserve</a></li>
            <li><a title="Blend of the Month Club" href="/e-liquid-cartridges/blend-of-the-month-club">Blend of the Month Club</a></li>
            <li><a title="Pre-filled Cartridges" href="/e-liquid-cartridges/pre-filled-cartridges">Pre-filled Cartridges</a></li>
        </ul>
    </li>


    <li class="nav-2 parent">
        <a href="/electronic-cigarettes" title="Electronic Cigarettes">Electronic Cigarettes</a>
        <a href="javascript: void(0)" class="sub-nav-btn"></a>
        <ul>
            <li class="sub">
                <a href="/electronic-cigarettes/e-liquid-devices">E-Liquid Devices</a>
                <ul class="sub-1">
                    <li><a href="/electronic-cigarettes/eliquid-devices" title="All E-Liquid Devices">All E-Liquid Devices</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-rocket" title="VaporFi Rocket">VaporFi Rocket</a></li>
                    <li><a href="/electronic-cigarettes/custom-vaporizer-builder" title="Custom Vaporizer/MOD Builder">Custom Vaporizer/MOD Builder</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-vice" title="VaporFi Vice Starter Kit">VaporFi Vice Starter Kit</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-edge" title="VaporFi Edge">VaporFi Edge</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-pro-ii-in-colors" title="VaporFi VOX 100 TC MOD">VaporFi VOX 100 TC MOD</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-express" title="VaporFi Express">VaporFi Express</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-vox-ii-mod" title="VaporFi VOX II MOD">VaporFi VOX II MOD</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-platinum-pro" title="VaporFi Platinum Pro">VaporFi Platinum Pro</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-vox-ii-starter-kit" title="VaporFi VOX II Starter Kit">VaporFi VOX II Starter Kit</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-pro-ii" title="VaporFi Pro II">VaporFi Pro II</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-vox-mini-mod" title="VaporFi VOX Mini MOD">VaporFi VOX Mini MOD</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-pro-ii-in-colors" title="VaporFi Pro II Starter Kit (in Colors)">VaporFi Pro II (in Colors)</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-vox-ii-starter-kit" title="VaporFi VOX Mini Starter Kit">VaporFi VOX Mini Starter Kit</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-rebel-ii" title="VaporFi Rebel II">VaporFi Rebel II</a></li>
                </ul>
            </li>
            <li class="sub">
                <a href="/electronic-cigarettes/dry-herb-devices">Dry Herb Devices</a>
                <ul class="sub-2 clearer">
                    <li><a href="/electronic-cigarettes/dry-herb-devices" title="All Dry Herb Devices">All Dry Herb Devices</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-stratus" title="VaporFi Stratus">VaporFi Stratus</a></li>
                    <li><a href="/electronic-cigarettes/vaporfi-orbit" title="VaporFi Orbit">VaporFi Orbit</a></li>
                </ul>
            </li>
            <li><a href="/electronic-cigarettes/advanced-vaporizers" title="Advanced Vaporizers">Advanced Vaporizers</a></li>
            <li><a href="/electronic-cigarettes" title="All Electronic Cigarettes">All Electronic Cigarettes</a></li>
        </ul>
    </li>

    <li class="nav-3 parent">
        <a href="/accessories" title="Accessories">Accessories</a>
        <a href="javascript: void(0)" class="sub-nav-btn"></a>
        <ul>
            <li class="sub">
                <a href="/accessories/batteries" title="Batteries">Batteries</a>
                <ul class="sub-1">
                    <li><a href="#">All Batteries</a></li>
                    <li><a href="#">Air Batteries</a></li>
                    <li><a href="#">Edge Batteries</a></li>
                    <li><a href="#">Express Batteries</a></li>
                    <li><a href="#">MOD Batteries</a></li>
                    <li><a href="#">Pro Batteries</a></li>
                    <li><a href="#">Rebel Batteries</a></li>
                    <li><a href="#">Rocket Batteries</a></li>
                    <li><a href="#">Vice Batteries</a></li>
                </ul>
            </li>
            <li class="sub">
                <a href="#" title="Chargers">Chargers</a>
                <ul class="sub-2">
                    <li><a href="#">All Chargers</a></li>
                    <li><a href="#">Air Chargers</a></li>
                    <li><a href="#">Boom Chargers</a></li>
                    <li><a href="#">Express Chargers</a></li>
                    <li><a href="#">MOD Chargers</a></li>
                    <li><a href="#">Pro Chargers</a></li>
                    <li><a href="#">Pulse Chargers</a></li>
                    <li><a href="#">Rebel Chargers</a></li>
                    <li><a href="#">Rocket Chargers</a></li>
                </ul>
            </li>
            <li class="sub">
                <a href="#" title="Tanks">Tanks</a>
                <ul class="sub-3">
                    <li><a href="#">All Tanks</a></li>
                    <li><a href="#">Boom Tanks</a></li>
                    <li><a href="#">Edge Tanks</a></li>
                    <li><a href="#">Express Tanks</a></li>
                    <li><a href="#">Pro Tanks</a></li>
                    <li><a href="#">Pulse Tanks</a></li>
                    <li><a href="#">RDA/RBA</a></li>
                    <li><a href="#">Rebel Tanks</a></li>
                    <li><a href="#">Rocket Tanks</a></li>
                    <li><a href="#">Vice Tanks</a></li>
                    <li><a href="#">VOX MOD Tanks</a></li>
                </ul>
            </li>
            <li class="sub">
                <a href="#" title="Atomizers &amp; Cartomizers">Atomizers &amp; Cartomizers</a>
                <ul class="sub-4">
                    <li><a href="#">All Atomizers &amp; Cartomizers</a></li>
                    <li><a href="#">Bolt RDA</a></li>
                    <li><a href="#">Edge Atomizer Heads</a></li>
                    <li><a href="#">Express Cartomizers</a></li>
                    <li><a href="#">Pro &amp; Platinum Atomizer Heads</a></li>
                    <li><a href="#">Pulse Atomizer Heads</a></li>
                    <li><a href="#">Rebel Atomizer Heads</a></li>
                    <li><a href="#">Titanium &amp; Rocket Tank Atomizer</a></li>
                    <li><a href="#">Vice Atomizer Heads</a></li>
                    <li><a href="#">Volt Atomizers &amp; Coils</a></li>
                    <li><a href="#">vShock Atomizer Heads</a></li>
                    <li><a href="#">vSix Atomizer Heads</a></li>
                </ul>
            </li>
            <li class="sub">
                <a href="#" title="Other">Other</a>
                <ul class="sub-5">
                    <li><a href="#">Advanced Accessories</a></li>
                    <li><a href="#">Apparel</a></li>
                    <li><a href="#">Cases &amp; Lanyards</a></li>
                    <li><a href="#">Drip Tips</a></li>
                    <li><a href="#">Gift Cards</a></li>
                    <li><a href="#">Parts &amp; Tools</a></li>
                </ul>
            </li>
            <li><a href="#" title="All Accessories">All Accessories</a></li>
        </ul>
    </li>

    <li class="nav-4 parent">
        <a title="How It Works" href="/how-it-works">How It Works</a>
        <a href="javascript: void(0)" class="sub-nav-btn"></a>
        <ul>
            <li><a title="How E-Cigs Work" href="/how-it-works">How E-Cigs Work</a></li>
            <li><a title="Why Our e-Liquid Rocks" href="/how-it-works/why-e-liquid-rocks">Why Our e-Liquid Rocks</a></li>
            <li><a title="Compare Models" href="/how-it-works/compare">Compare Models</a></li>
            <li><a title="Instructional Videos" href="/how-it-works/videos">Instructional Videos</a></li>
            <li><a title="Tips for Success" href="/how-it-works/tips-for-success">Tips for Success</a></li>
            <li><a title="Home Delivery Program" href="/enroll">Home Delivery Program</a></li>
            <li><a title="Rewards" href="/how-it-works/rewards">Vapor Rewards</a></li>
            <li><a title="FAQ" href="/how-it-works/faq">FAQ</a></li>
            <li><a title="Learning Center" href="/how-it-works/learn">Learning Center</a></li>
            <li><a title="Refer-a-Friend" href="/refer-a-friend">Refer-a-Friend</a></li>
        </ul>
    </li>

    <li class="nav-5 parent">
        <a title="About Us" href="/our-company">About Us</a>
        <a href="javascript: void(0)" class="sub-nav-btn"></a>
        <ul>
            <li><a title="Our Company" href="/our-company">Our Company</a></li>
            <li><a title="In the News" href="/our-company/news">In the News</a></li>
            <li><a title="Review Sites" href="/our-company/review-sites">Review Sites</a></li>
            <li><a title="Testimonials" href="/our-company/testimonials">Testimonials</a></li>
            <li><a title="Affiliate Program" href="#">Affiliate Program</a></li>
            <li><a title="Wholesale Opportunities" href="/wholesale">Wholesale</a></li>
            <li><a title="Careers" href="http://www.vaporfi.com/careers/">Careers</a></li>
            <li><a title="Franchising" href="/our-company/franchising">Franchising</a></li>
            <li><a title="Email Deals" href="/our-company/newsletter">Email Deals</a></li>
            <li><a title="Blog" href="#" target="_blank">Blog</a></li>
        </ul>
    </li>
</ul>



<!-- FOOTER MENU -->
<div class="footerContent clearer first">
    <a class="header-link" href="/e-liquid-cartridges">E-Liquid &amp; Cartridges</a>
    <ul>
        <li><a title="Custom Blending" href="/e-liquid-cartridges/custom-blending">Custom Blending</a></li>
        <li><a title="Sampler 3-Pack" href="/e-liquid-cartridges/sampler-3-pack">Sampler 3-Pack</a></li>
        <li><a title="Top Blends" href="/e-liquid-cartridges/top-blends">Top Blends</a></li>
        <li>
            <a href="/e-liquid-cartridges/reserve-collection">Reserve &amp; Grand Reserve</a>
            <ul>
                <li><a href="#">Reserve Collection</a></li>
                <li><a href="#">Grand Reserve Collection</a></li>
            </ul>
        </li>
        <li><a title="Tobacco Flavors" href="/e-liquid-cartridges/tobacco-flavors">Tobacco Flavors</a></li>
        <li><a title="Menthol Flavors" href="/e-liquid-cartridges/menthol-flavors">Menthol Flavors</a></li>
        <li><a title="Fruit Flavors" href="/e-liquid-cartridges/fruit-flavors">Fruit Flavors</a></li>
        <li><a title="Dessert Flavors" href="/e-liquid-cartridges/dessert-flavors">Dessert Flavors</a></li>
        <li><a title="Other Flavors" href="/e-liquid-cartridges/other-flavors">Other Flavors</a></li>
        <li><a title="Flavor Enhancers" href="/e-liquid-cartridges/flavor-enhancers">Flavor Enhancers</a></li>
        <li><a title="Reserve &amp; Grand Reserve Collection" href="/e-liquid-cartridges/reserve-collection">Reserve &amp; Grand Reserve</a></li>
        <li><a title="Blend of the Month Club" href="/e-liquid-cartridges/blend-of-the-month-club">Blend of the Month Club</a></li>
        <li><a title="Pre-filled Cartridges" href="/e-liquid-cartridges/pre-filled-cartridges">Pre-filled Cartridges</a></li>
    </ul>
</div>
<div class="footerContent clearer">
    <a class="header-link" href="/electronic-cigarettes">Electronic Cigarettes</a>
    <ul>
        <li><a href="/electronic-cigarettes/eliquid-devices" title="All E-Liquid Devices">All E-Liquid Devices</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-rocket" title="VaporFi Rocket">VaporFi Rocket</a></li>
        <li><a href="/electronic-cigarettes/custom-vaporizer-builder" title="Custom Vaporizer/MOD Builder">Custom Vaporizer/MOD Builder</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-vice" title="VaporFi Vice Starter Kit">VaporFi Vice Starter Kit</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-edge" title="VaporFi Edge">VaporFi Edge</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-pro-ii-in-colors" title="VaporFi VOX 100 TC MOD">VaporFi VOX 100 TC MOD</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-express" title="VaporFi Express">VaporFi Express</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-vox-ii-mod" title="VaporFi VOX II MOD">VaporFi VOX II MOD</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-platinum-pro" title="VaporFi Platinum Pro">VaporFi Platinum Pro</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-vox-ii-starter-kit" title="VaporFi VOX II Starter Kit">VaporFi VOX II Starter Kit</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-pro-ii" title="VaporFi Pro II">VaporFi Pro II</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-vox-mini-mod" title="VaporFi VOX Mini MOD">VaporFi VOX Mini MOD</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-pro-ii-in-colors" title="VaporFi Pro II Starter Kit (in Colors)">VaporFi Pro II (in Colors)</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-vox-ii-starter-kit" title="VaporFi VOX Mini Starter Kit">VaporFi VOX Mini Starter Kit</a></li>
        <li><a href="/electronic-cigarettes/vaporfi-rebel-ii" title="VaporFi Rebel II">VaporFi Rebel II</a></li>
    </ul>
</div>
<div class="footerContent footerContent2 clearer">
    <a class="header-link" href="/accessories">Accessories</a>
    <ul>
        <li>
            <a href="/accessories/batteries">Batteries</a>
            <ul>
                <li><a href="#">All Batteries</a></li>
                <li><a href="#">Air Batteries</a></li>
                <li><a href="#">Edge Batteries</a></li>
                <li><a href="#">Express Batteries</a></li>
                <li><a href="#">MOD Batteries</a></li>
                <li><a href="#">Pro Batteries</a></li>
                <li><a href="#">Rebel Batteries</a></li>
                <li><a href="#">Rocket Batteries</a></li>
                <li><a href="#">Vice Batteries</a></li>
            </ul>
        </li>
        <li>
            <a href="#">Chargers</a>
            <ul>
                <li><a href="#">All Chargers</a></li>
                <li><a href="#">Air Chargers</a></li>
                <li><a href="#">Boom Chargers</a></li>
                <li><a href="#">Express Chargers</a></li>
                <li><a href="#">MOD Chargers</a></li>
                <li><a href="#">Pro Chargers</a></li>
                <li><a href="#">Rebel Chargers</a></li>
                <li><a href="#">Pulse Chargers</a></li>
                <li><a href="#">Rocket Chargers</a></li>
            </ul>
        </li>
    </ul>
    <ul>
        <li>
            <a href="#">Tanks</a>
            <ul>
                <li><a href="#">All Tanks</a></li>
                <li><a href="#">Boom Tanks</a></li>
                <li><a href="#">Edge Tanks</a></li>
                <li><a href="#/">Express Tanks</a></li>
                <li><a href="#">Pro Tanks</a></li>
                <li><a href="#">Pulse Tanks</a></li>
                <li><a href="#">RDA/RBA</a></li>
                <li><a href="#">Rebel Tanks</a></li>
                <li><a href="#">Rocket Tanks</a></li>
                <li><a href="#">Vice Tanks</a></li>
                <li><a href="#">VOX MOD Tanks</a></li>
            </ul>
        </li>
        <li>
            <a href="#">Atomizers &amp; Cartomizers</a>
            <ul>
                <li><a href="#"> All Atomizers &amp; Cartomizers</a></li>
                <li><a href="#">Bolt RDA</a></li>
                <li><a href="#">Edge Atomizer Heads</a></li>
                <li><a href="#">Express Cartomizers</a></li>
                <li><a href="#">Pro &amp; Platinum Atomizer Heads</a></li>
                <li><a href="#">Pulse Atomizer Heads</a></li>
                <li><a href="#">Rebel Atomizer Heads</a></li>
                <li><a href="#">Titanium &amp; Rocket Atomizer</a></li>
                <li><a href="#">Vice Atomizer Heads</a></li>
                <li><a href="#">Volt Atomizers &amp; Coils</a></li>
                <li><a href="#">vShock Atomizer Heads</a></li>
            </ul>
        </li>
        <li>
            <a href="#">Other</a>
            <ul>
                <li><a href="#/">Advanced Accessories</a></li>
                <li><a href="#">Apparel</a></li>
                <li><a href="#">Cases &amp; Lanyards</a></li>
                <li><a href="#">Drip Tips</a></li>
                <li><a href="#">Gift Cards</a></li>
                <li><a href="#">Parts &amp; Tools</a></li>
            </ul>
        </li>
    </ul>
</div>
<div class="footerContent clearer">
    <a class="header-link" href="/how-it-works">How It Works</a>
    <ul>
        <li><a title="How E-Cigs Work" href="/how-it-works">How E-Cigs Work</a></li>
        <li><a title="Why Our e-Liquid Rocks" href="/how-it-works/why-e-liquid-rocks">Why Our e-Liquid Rocks</a></li>
        <li><a title="Compare Models" href="/how-it-works/compare">Compare Models</a></li>
        <li><a title="Instructional Videos" href="/how-it-works/videos">Instructional Videos</a></li>
        <li><a title="Tips for Success" href="/how-it-works/tips-for-success">Tips for Success</a></li>
        <li><a title="Home Delivery Program" href="/enroll">Home Delivery Program</a></li>
        <li><a title="Rewards" href="/how-it-works/rewards">Vapor Rewards</a></li>
        <li><a title="FAQ" href="/how-it-works/faq">FAQ</a></li>
        <li><a title="Learning Center" href="/how-it-works/learn">Learning Center</a></li>
        <li><a title="Refer-a-Friend" href="/refer-a-friend">Refer-a-Friend</a></li>
    </ul>
</div>
<div class="footerContent clearer last">
    <a class="header-link" href="/our-company">Our Company</a>
    <ul>
        <li><a title="Our Company" href="/our-company">Our Company</a></li>
        <li><a title="In the News" href="/our-company/news">In the News</a></li>
        <li><a title="Review Sites" href="/our-company/review-sites">Review Sites</a></li>
        <li><a title="Testimonials" href="/our-company/testimonials">Testimonials</a></li>
        <li><a title="Affiliate Program" href="#">Affiliate Program</a></li>
        <li><a title="Wholesale Opportunities" href="/wholesale">Wholesale</a></li>
        <li><a title="Careers" href="http://www.vaporfi.com/careers/">Careers</a></li>
        <li><a title="Franchising" href="/our-company/franchising">Franchising</a></li>
        <li><a title="Email Deals" href="/our-company/newsletter">Email Deals</a></li>
        <li><a title="Blog" href="#" target="_blank">Blog</a></li>
    </ul>
</div>