<div class="onepageSection" id="onepageSection">
    <form action="" id="co-shipping-form" class="checkout-center">
        <h2><?=$this->__("Shipping Address");?></h2>
        <ul class="form-list">
        <?php if ($this->customerHasAddresses()): ?>
           <li class="wide">
               <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
               <div class="input-box">
                   <?php echo $this->getAddressesHtmlSelect('shipping') ?>
               </div>
           </li>
        <?php endif ?>
            <li class="cart-address" id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
                <fieldset>
                    <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                    <ul>
                        <li class="fields fieldset" id="shipping-customer-name">
                            <?=$this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml();?>
                        </li>
                        <li class="fields" style="display:none;">
                            <div class="fields">
                                <label for="shipping:company"><?php echo $this->__('Company') ?></label>
                                <div class="input-box">
                                    <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                        </li>
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                        <li class="fields">
                            <div class="input-box">
                                <input type="text" title="<?=Mage::helper('core')->quoteEscape($this->__('Street Address'));?>" placeholder="<?=Mage::helper('core')->quoteEscape($this->__('STREET ADDRESS 1'));?>"
                                    name="shipping[street][]" id="shipping:street1" value="<?=$this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
                                        class="input-text <?=$_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </li>
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <li class="fields">
                            <div class="input-box">
                                <input type="text" title="<?=Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i));?>" placeholder="<?=Mage::helper('core')->quoteEscape($this->__('STREET ADDRESS 2'));?>"
                                    name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
                                        class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </li>
                <?php endfor; ?>
                        <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                        <li class="fields">
                            <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                            <div class="input-box">
                                <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('VAT Number')); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                            </div>
                        </li>
                        <?php endif; ?>
                        <li class="fields">
                            <div class="input-box">
                                <input type="text" title="<?=Mage::helper('core')->quoteEscape($this->__('City'));?>" placeholder="CITY"
                                    name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
                                        class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city"
                                            onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </li>
                        <li class="fields fieldset">
                            <div class="field">
                                <div class="input-box select-box">
                                    <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                    </select>
                                    <script type="text/javascript">
                                        //<![CDATA[
                                        $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                        //]]>
                                    </script>
                                    <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
                                        title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" placeholder="STATE/PROVINCE"
                                            class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                                </div>
                            </div>
                            <div class="field last">
                                <div class="input-box">
                                    <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" placeholder="ZIP CODE"
                                        name="shipping[postcode]" id="shipping:postcode" value="<?=$this->escapeHtml($this->getAddress()->getPostcode()) ?>"
                                            class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"
                                                onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="input-box select-box">
                                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="input-box">
                                <input type="tel" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" placeholder="PHONE NUMBER"
                                    title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>"
                                        id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </li>
                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                        <li class="control">
                            <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save in address book')) ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></li>
                    <?php else:?>
                        <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                    <?php endif;?>
                    </ul>
                </fieldset>
            </li>

        </ul>

        <div id="shipping-buttons-container" class="please-wait-loader">
            <span id="shipping-please-wait" class="please-wait" style="display:none;">
                <img src="/skin/frontend/default/vaporfi_theme/images/opc-ajax-loader.gif" alt="Loading next step..." title="Loading step..." class="v-middle">
                <?=$this->__('Loading step...');?>
            </span>
        </div>

    </form>

    <?=$this->getChildHtml('shipping_method');?>

    <form class="checkout-buttons">
        <div class="buttons-set">
            <button type="button" class="greenButton continueBtn" onclick="shipping.save()" id="shipping-save-btn">
                <?=$this->__('Continue') ?>
            </button>
            <button type="button" class="lgrayButton backBtn" onclick="location.href='/'">
                <?=$this->__('Shop More');?>
            </button>
        </div>
    </form>

    <script type="text/javascript">
        //<![CDATA[
        var shipping = new Shipping('co-shipping-form', '<?=$this->getUrl('checkout/onepage/getAddress') ?>address/', '<?=$this->getUrl('checkout/onepage/saveShipping') ?>',
            '<?=$this->getUrl('checkout/onepage/shippingMethod') ?>');
        var shippingForm = new VarienForm('co-shipping-form');
        shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
        //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?=$this->getUrl('directory/json/childRegion') ?>', '<?=Mage::helper('core')->jsQuoteEscape($this->__('Select State/Province...'))?>');
        $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

        var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?=$this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
        //]]>
    </script>

    <div id="shipping-buttons-container-bottom" class="please-wait-loader">
        <span id="shipping-please-wait-bottom" class="please-wait" style="display:none;">
            <img src="/skin/frontend/default/vaporfi_theme/images/opc-ajax-loader.gif" alt="Loading next step..." title="Loading step..." class="v-middle">
                <?=$this->__('Loading step...');?>
        </span>
    </div>

</div>
