<div id="footer-links">
    <div class="wrapper clearer">

        <?=$this->getLayout()->createBlock('cms/block')->setBlockId('footer-menu')->toHtml()?>

    </div>

    <div id="siteInfo" class="site-info-toggle">
        <h1>Shop for E-Liquids<br> VaporFi - Best Place for Custom E-Cigarette Juice</h1>
        <h3> Customizable E-Cigarettes and E-Liquid</h3>
        <p>Part of the International Vapor Group, VaporFi is the industry’s premier manufacturer and retailer of cutting-edge <a href="#" title="buy e-cigarettes">electronic cigarettes</a>, <a href="#" title="buy e-cig accessories">e-cig accessories</a> and <a href="#" title="shop e-liquid">nicotine e-liquid</a>. Visitors to our brick-and-mortar locations enjoy a vast selection of customizable e-liquid flavors – over 30,000 flavor combinations in fact! Online patrons also enjoy the ability to mix their own e-liquid blends, and take advantage of all that e-cigarettes have to offer.</p>
        <h3>Find the Perfect Blend with VaporFi E-Juices</h3>
        <p>Have you tried what seems like dozens of e-juice combinations but have yet to find the right flavor? VaporFi e-juice bars allow you to run wild with over <a href="#" title="30,000+ e-liquid combinations">30,000+ e-liquid combinations</a> available. Many entry-level e-cigs do not allow you to customize the flavor and taste of the <a href="#" title="nicotine e-juice">nicotine e-juice</a>. While there are options in the form of pre-filled cartridges, blending your own <a href="#" title="e-juice">e-juice</a> takes vaping to a whole other level. </p>
        <h3>Vapor Cigarette Franchising Opportunities </h3>
        <p>Are you a passionate e-smoker who would like to take advantage of opportunities in this emerging electronic cigarette industry? Do you live in an area where <a href="#" title="Vapor Cigarettes">vapor cigarettes</a> would be popular, but are not easily available? Consider a <a href="#" title="vapor e-cig franchise">vapor store franchise</a> with VaporFi. Bring custom e-liquid blending and cutting-edge vapor cigarette devices to your community today. Not only are VaporFi <a href="#" title="e-Cigs from Vaporfi">e-smoking devices</a> some of the most durable, they’re made right here in the USA along with all of our flavored e-liquids.</p>
        <p style="text-align:center">Shop online: <a href="#" title="electronic cigarettes">E-cigarettes</a> | <a href="#" title="e-liquids">E-liquid</a> | <a href="#" title="Buy e-cig juice">Top E-liquid Blends</a> | <a href="#" title="electronic cigarette juice franchise">Vapor Cigarette Liquid Franchise</a> | <a href="#" title="custom-e-liquid">Custom E-Cigarette Liquid </a> | <a href="#" title="e-cigarette-starter-kits">E-Cigarette Starter Kits </a> | <a href="#" title="VaporFi vaporizer cigarettes">Vaporizer Cigarettes </a> | <a href="#" title="Buy VaporFi digital cigarettes">Digital Cigarettes </a>
            <br>
            <a href="#" title="Customizable Electronic Cigarettes">Customizable Electronic Cigarettes</a> | <a href="#" title="Electronic Vapor Smoking">Electronic Vapor Smoking</a>
        </p>
    </div>
</div>