<header>

    <div id="top">
        <div id="topWrapper">
            <a href="javascript: void(0)" id="m-cart-btn"><span id="m-cart">7</span></a>
            <a href="/" title="VaporFi" id="logo">
                <img src="/skin/frontend/default/vaporfi_theme/images/logo.png" alt="VaporFi" width="256" height="97">
            </a>
            <div id="topMenuContainer">
                <div id="checkoutMenu">
                    <h4 id="checkout-step-1" class="complete"><span>Step 1</span> Account</h4>
                    <h4 id="checkout-step-2" class="selected"><span>Step 2</span> Shipping</h4>
                    <h4 id="checkout-step-3"><span>Step 3</span> Payment</h4>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>

</header>